---
name: sse-rooms-redis

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/sse-rooms-redis/**'
      - 'lib/sse/rooms/**'
  push:
    branches:
      - main
    paths:
      - 'packages/sse-rooms-redis/**'
      - 'lib/sse/rooms/**'

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: packages/sse-rooms-redis

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.x

      - name: Install all dependencies
        run: npm install
        working-directory: .

      - name: Build root package
        run: npm run build
        working-directory: .

      - name: Run Tests
        run: npm test

      - name: Run Linting
        run: npm run lint
